import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
cfg = json.loads((root / "config" / "default.json").read_text(encoding="utf-8"))
lines = []
a = lines.append
a("// Auto-derived from net-lab packages/core/config.ts defaults. Do not hand-edit parity literals.")
a("// Source: config/default.json. configHash target: 6c3a8288f02919a3")
a("using System;")
a("using System.Collections.Generic;")
a("using NetNinja.Contracts;")
a("namespace NetNinja.Core")
a("{")
a("    public sealed class CoreConfig : CoreConfigView")
a("    {")
a("        readonly Dictionary<string, object> _map = new Dictionary<string, object>();")
a("")
a("        public CoreConfig() { }")
a("")
a("        public static CoreConfig CreateDefault() => FromMap(DefaultMap());")
a("")
a("        public CoreConfig Clone() => FromMap(new Dictionary<string, object>(_map));")
a("")
a("        public static CoreConfig FromMap(Dictionary<string, object> map)")
a("        {")
a("            var c = new CoreConfig();")
a("            foreach (var kv in map) c._map[kv.Key] = kv.Value;")
a("            return c;")
a("        }")
a("")
a("        public IEnumerable<string> SortedKeys()")
a("        {")
a("            var keys = new List<string>(_map.Keys);")
a("            keys.Sort(StringComparer.Ordinal);")
a("            return keys;")
a("        }")
a("")
a("        public object Raw(string key) => _map[key];")
a("        public void Set(string key, object value) => _map[key] = value;")
a("")
a("        public double GetDouble(string key)")
a("        {")
a("            var v = _map[key];")
a("            if (v is double d) return d;")
a("            if (v is int i) return i;")
a("            if (v is long l) return l;")
a("            return Convert.ToDouble(v);")
a("        }")
a("        public bool GetBool(string key) => (bool)_map[key];")
a("        public string GetString(string key) => Convert.ToString(_map[key]);")
a("        public double D(string key) => GetDouble(key);")
a("        public bool B(string key) => GetBool(key);")
a("        public string S(string key) => GetString(key);")
a("        public int I(string key) => (int)GetDouble(key);")
a("")
a("        public static Dictionary<string, object> DefaultMap()")
a("        {")
a("            return new Dictionary<string, object>")
a("            {")
for k, v in cfg.items():
    if isinstance(v, bool):
        lit = "true" if v else "false"
        a(f'                ["{k}"] = {lit},')
    elif isinstance(v, str):
        a(f'                ["{k}"] = "{v}",')
    else:
        lit = repr(float(v))
        a(f'                ["{k}"] = {lit},')
a("            };")
a("        }")
a("    }")
a("}")
out = root / "Packages" / "com.netninja.core" / "Runtime" / "CoreConfig.cs"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote", out, "keys", len(cfg))
